(global-unset-key (kbd "M-m"))

(defun clock-start ()
  (interactive)
  (slime-interactive-eval "(calispel:! midihelper:*clock-ctrl-chan* (midihelper:ev-start))"))
(defun clock-stop ()
  (interactive)
  (slime-interactive-eval "(calispel:! midihelper:*clock-ctrl-chan* (midihelper:ev-stop))"))
(defun clock-continue ()
  (interactive)
  (slime-interactive-eval "(calispel:! midihelper:*clock-ctrl-chan* (midihelper:ev-continue))"))
(global-set-key (kbd "M-m M-m") 'clock-stop)
(global-set-key (kbd "M-m M-k") 'clock-continue)
(global-set-key (kbd "M-m M-l") 'clock-start)

(defun group1 ()
  (interactive)
  (slime-interactive-eval "(calispel:! midihelper:*clock-ctrl-chan* (mloops::global-ctrl (lambda () (mloops::loop-group 1))))"))
(defun loop1 ()
  (interactive)
  (slime-interactive-eval "(setf mloops::*active-loop* 1)"))
(defun group2 ()
  (interactive)
  (slime-interactive-eval "(calispel:! midihelper:*clock-ctrl-chan* (mloops::global-ctrl (lambda () (mloops::loop-group 2))))"))
(defun loop2 ()
  (interactive)
  (slime-interactive-eval "(setf mloops::*active-loop* 2)"))
(defun group3 ()
  (interactive)
  (slime-interactive-eval "(calispel:! midihelper:*clock-ctrl-chan* (mloops::global-ctrl (lambda () (mloops::loop-group 3))))"))
(defun loop3 ()
  (interactive)
  (slime-interactive-eval "(setf mloops::*active-loop* 3)"))
(defun group4 ()
  (interactive)
  (slime-interactive-eval "(calispel:! midihelper:*clock-ctrl-chan* (mloops::global-ctrl (lambda () (mloops::loop-group 4))))"))
(defun loop4 ()
  (interactive)
  (slime-interactive-eval "(setf mloops::*active-loop* 4)"))
(global-set-key (kbd "M-m 1") 'loop1)
(global-set-key (kbd "M-m M-1") 'group1)
(global-set-key (kbd "M-m 2") 'loop2)
(global-set-key (kbd "M-m M-2") 'group2)
(global-set-key (kbd "M-m 3") 'loop3)
(global-set-key (kbd "M-m M-3") 'group3)
(global-set-key (kbd "M-m 4") 'loop4)
(global-set-key (kbd "M-m M-4") 'group4)

(defun notekick ()
  (interactive)
  (slime-interactive-eval "(calispel:! midihelper:*reader-ochan* (midihelper:ev-noteon 0 36 127))"))
(defun notesnare ()
  (interactive)
  (slime-interactive-eval "(calispel:! midihelper:*reader-ochan* (midihelper:ev-noteon 0 38 127))"))
(defun noteclap ()
  (interactive)
  (slime-interactive-eval "(calispel:! midihelper:*reader-ochan* (midihelper:ev-noteon 0 39 127))"))
(defun note3 ()
  (interactive)
  (slime-interactive-eval "(calispel:! midihelper:*reader-ochan* (midihelper:ev-noteon 0 43 127))"))
(global-set-key (kbd "M-n") 'note3)
(global-set-key (kbd "M-j") 'notekick)
(global-set-key (kbd "M-k") 'notesnare)
(global-set-key (kbd "M-l") 'noteclap)

(defun toggle-metronome ()
  (interactive)
  (slime-interactive-eval "(mloops::global-ctrl #'mloops::toggle-metronome)"))
(global-set-key (kbd "M-m 0") 'toggle-metronome)

(defun midi-loop-cycle ()
  (interactive)
  (slime-interactive-eval "(calispel:! midihelper:*reader-ochan* (mloops::loop-ctrl #'mloops::loop-cycle))"))
(global-set-key (kbd "M-SPC") 'midi-loop-cycle)

(defun loop-play ()
  (interactive)
  (slime-interactive-eval "(calispel:! midihelper:*reader-ochan* (mloops::loop-ctrl #'mloops::loop-play))"))
(defun loop-play-push-extend ()
  (interactive)
  (slime-interactive-eval "(calispel:! midihelper:*reader-ochan* (mloops::loop-ctrl #'mloops::loop-push-extend))"))
(defun loop-stop ()
  (interactive)
  (slime-interactive-eval "(calispel:! midihelper:*reader-ochan* (mloops::loop-ctrl #'mloops::loop-stop))"))
(defun loop-erase ()
  (interactive)
  (slime-interactive-eval "(calispel:! midihelper:*reader-ochan* (mloops::loop-ctrl #'mloops::loop-erase))"))
(defun loop-overwrite ()
  (interactive)
  (slime-interactive-eval "(calispel:! midihelper:*reader-ochan* (mloops::loop-ctrl #'mloops::loop-overwrite))"))
(defun loop-overdub ()
  (interactive)
  (slime-interactive-eval "(calispel:! midihelper:*reader-ochan* (mloops::loop-ctrl #'mloops::loop-overdub))"))

(global-set-key (kbd "M-m m") 'loop-stop)
(global-set-key (kbd "M-m k") 'loop-continue)
(global-set-key (kbd "M-m l") 'loop-play)
(global-set-key (kbd "M-m d") 'loop-erase)
(global-set-key (kbd "M-m O") 'loop-overwrite)
(global-set-key (kbd "M-m o") 'loop-overdub)
(global-set-key (kbd "M-m l") 'loop-play-push-extend)
(global-set-key (kbd "M-m k") 'loop-play)


;; (define-derived-mode
;; (ido
;; (smex
;; smart parens
;; cider mode
;; redshank refactoring library
